vich_uploader:
    db_driver: orm

    mappings:
        videos:
            uri_prefix: /images/video
            upload_destination: '%kernel.project_dir%/public/images/videos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

